codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

flags:
  cpp:
    paths:
      - src/google/protobuf/
    carryforward: true
  java:
    paths:
      - java/
    carryforward: true
  python:
    paths:
      - python/google/protobuf/
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
